#!/bin/bash

set -e

release:prod() {
    release:test
    publish:prod
}


publish:prod() {
    load-dotenv

    DIRNAME=${1:-.}
    twine upload ${DIRNAME}/dist/* \
        -r pypi \
        --username=__token__ \
        --password="${PROD_PYPI_TOKEN}"

}


release:test() {
    DIRNAME=test_package
    clean ${DIRNAME}
    build ${DIRNAME}
    publish:test ${DIRNAME}
}


lint() {
    git add .; pre-commit run --all-files --show-diff-on-failure
}


lint:ci() {
    SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure
}



clean() {
    DIRNAME=${1:-.}
    rm -rf ${DIRNAME}/dist ${DIRNAME}/*.egg-info
 
}


build() {
    DIRNAME=${1:-.}
    python -m build ${DIRNAME}
}


publish:test() {
    try-load-dotenv || true

    DIRNAME=${1:-.}
    twine upload ./${DIRNAME}/dist/* \
        -r testpypi \
        --username=__token__ \
        --password="${TEST_PYPI_TOKEN}"

}


try-load-dotenv() {
    if [[ ! -f "./.env"  ]]; then
        echo "no .env file found." 
        return 1
    fi

    while read -r line; do
      
        export "$line"
    done < <(grep -v "^#" ./.env)

}


install() {
   pip install --upgrade pip && pip install -r requirements.txt
}


help() {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

echo ""
TIMEFORMAT="Task completed in %3lR" # this changes the env 'TIMEFORMAT' that 'time' uses
time ${@:-help} 
