[project]
name = "school"
authors = [{ name = "AJ", email = "test@test.com" }]
description = "School components like class and students."
readme = "README.md"
version = "0.0.2"
license = { text = "MIT" }
dependencies = [
    "rich<14",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["pytest"]
