name: Build, Test, and Publihs

on: 
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Linting
        run: |
          SKIP=no-commit-to-branch 

